#!/usr/bin/python

import argparse

def abv_calc(og, fg, simple=None):
    if (simple is None and og < fg + 0.05) or simple:
        return (og - fg) * 1.3125
    else:
        return (0.7608 * (og - fg) / (1.775 - og)) * (fg / 0.794)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('og', type=float, help='Original Gravity')
    parser.add_argument('fg', type=float, help='Final Gravity')

    args = parser.parse_args()
    abv = 100. * abv_calc(args.og, args.fg)
    print '{0:.02f}%'.format(abv)
